# Generated by Django 3.0.1 on 2020-05-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='hotspot',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='popularfood',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='img',
            new_name='image',
        ),
    ]
